export const list: string[] = [
  "🐃 Minotaur's Mountain Sprint",
  "👹 Gorgon's Gorge Sprint",
  "👀 Cyclops' Canyon Sprint",
  "🦅 Harpy's Highlands Sprint",
  "🦄 Pegasus' Plateau Sprint",
  "🐉 Sphinx's Summit Sprint",
  "🐻 Yeti's Yellowstone Sprint",
  "🐉🐍🐖 Chimera's Crater Sprint",
  "🐲 Basilisk's Battlefield Sprint",
  "🛡 Valkyrie's Vale Sprint",
  "🐉 Dragon's Den Sprint",
  "🧜‍♀️ Mermaid's Maze Sprint",
  "🦅 Gryphon's Gauntlet Sprint",
  "🔥 Phoenix's Flight Sprint",
  "🦄 Unicorn's Utopia Sprint",
  "🦑 Kraken's Krawl Sprint",
  "🎤 Siren's Song Sprint",
  "👹 Giant's Grotto Sprint",
  "🧚‍♀️ Nymph's Nook Sprint",
  "🐎 Centaur's Canyon Sprint",
  "🏹 Archer's Arrow Sprint",
  "🐉 Dragon's Lair Sprint",
  "🦅 Eagle's Eyrie Sprint",
  "🦄 Unicorn's Glen Sprint",
  "🐲 Dragon's Den Sprint",
  "🐉 Serpent's Pass Sprint",
  "🐺 Wolf's Wood Sprint",
  "🐃 Bull's Bluff Sprint",
  "🦂 Scorpion's Swale Sprint",
  "🐊 Crocodile's Creek Sprint",
  "🐎Horse's Hollow Sprint",
  "🐘Elephant's End Sprint",
  "🦏Rhino's Ridge Sprint",
  "🐍Serpent's Swirl Sprint",
  "🐊Alligator's Alley Sprint",
  "🐆Leopard's Leap Sprint",
  "🦁Lion's Den Sprint",
  "🐻Bear's Bellows Sprint",
  "🐒Monkey's Mound Sprint",
  "🦍Gorilla's Grotto Sprint",
];
